{
 "title": "IAVL",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Set KV Duration (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iavl_set_kv_duration_seconds_sum[5m])/rate(iavl_set_kv_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Average Save Version IAVL Duration (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iavl_save_version_duration_seconds_sum[5m])/rate(iavl_save_version_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Rate Set KV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(iavl_total_kv[30s])" }
   ]
  },
  {
   "title": "Total kv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "iavl_total_kv" }
   ]
  }
 ]
}